spring:
  ai:
    openai:
      api-key: ${API_KEY}
      embedding:
        api-key: ${API_KEY}
  application:
    name: recommendation
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
  config:
    import: optional:configserver:http://localhost:8888
  profiles:
    active: dev